### ISSUE TITLE
Add suport for Swedish

### ISSUE THREAD

**Issue by Nedok** [Indimeco/Tabletop-Simulator-Misc#3]
Please Add support for Swedish (And Finnish, Estonian, German as it isn't so different)

Is this what you need to add a new language?

ÄÖäö   -   Finnish
ÅÄÖåäö   -   Swedish
é   -   Swedish (Uncommon characters)
ÄÖÕÜäöõü   -   Estonian
ÄÖÜäöüß   -   German

Compacted character list
ÅÄÖÕÜ
åäöõü
éß

---- One Line Test ----

AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA = 37
ÅÅÅÅÅÅÅÅÅÅÅÅÅÅÅÅÅÅÅÅÅÅÅÅÅÅÅÅÅÅÅÅÅÅÅÅ = 37
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ = 37

aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa = 40
ååååååååååååååååååååååååååååååååååååååå = 40
äääääääääääääääääääääääääääääääääääääää = 40

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO = 32
ÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖÖ = 32
ÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕÕ = 32

UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU = 34
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ = 34

uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu = 40
üüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüüü = 40

ßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßßß = 37

eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee = 47
éééééééééééééééééééééééééééééééééééééééééééééé = 47

--- Result ---
A, Å, Ä	= 37
a, å, ä	= 40
O, Ö, Õ	= 32
U, Ü		= 34
e, é		= 47
ß		= 37

**Comment by Indimeco** [comment]
Hello, thank you for the data. I have added these characters to the script.
I know the mod isn't perfect, but I hope you get some use out of it!
